// ## /auth
@api_base = http://localhost:3000/api
@access_token = 17dfbf0dd1c116a217dfbf0dd1c16907
@refresh_token = 17dfb982a9b1a16c17dfb982a9b1cca3

# ==============================================================================

### menus request
GET {{api_base}}/menus HTTP/1.1
authorization: Bearer {{access_token}}

# ==============================================================================

### password grant success
POST {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "grant_type": "password",
  "username": "zce",
  "password": "wanglei"
}

### password grant failed
POST {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "grant_type": "password",
  "username": "zce",
  "password": "wanglei1"
}

### refresh token success
POST {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "grant_type": "refresh_token",
  "refresh_token": "{{refresh_token}}"
}

### refresh token failed
POST {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "grant_type": "refresh_token",
  "refresh_token": "invalid token"
}

### invalid grant type
POST {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "grant_type": "foo"
}

### revoke refresh token success
DELETE {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "token": "17b1ac3005b18f3f17b1ac3005b1cb22"
}

### revoke refresh token failed
DELETE {{api_base}}/auth/token HTTP/1.1
content-type: application/json

{
  "token": "foo"
}

# ==============================================================================

### Playground
GET https://api.github.com/gists/starred HTTP/1.1
Authorization: Bearer sssss
