export const CHANGE_TITLE = 'CHANGE_TITLE'

export const CHANGE_SESSION = 'CHANGE_SESSION'

export const TOGGLE_SIDEBAR_COLLAPSE = 'TOGGLE_SIDEBAR_COLLAPSE'

export const CHANGE_BREADCRUMBS = 'CHANGE_BREADCRUMBS'

export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'
